# Generated by Django 2.2.5 on 2019-12-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alghani', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminteam',
            name='desc',
        ),
        migrations.AddField(
            model_name='adminteam',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminteam',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
