# Generated by Django 2.2.6 on 2019-11-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191113_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='list6',
        ),
        migrations.RemoveField(
            model_name='service',
            name='list7',
        ),
    ]
