# Generated by Django 2.2.6 on 2019-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191113_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='list1',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='service',
            name='list2',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='service',
            name='list3',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='service',
            name='list4',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='service',
            name='list5',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
