# Generated by Django 2.2.6 on 2019-12-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191113_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='list1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='list2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='list3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='list4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='list5',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
