# Generated by Django 2.2.6 on 2019-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20191205_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='list1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='list2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='list3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='list4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='list5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
