# Generated by Django 2.2.6 on 2019-12-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20191205_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='list5',
        ),
    ]
