# Generated by Django 2.2.6 on 2019-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20191205_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='list5',
            field=models.TextField(blank=True),
        ),
    ]
