# Generated by Django 2.2.6 on 2019-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_list5'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='list6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='list7',
            field=models.TextField(blank=True),
        ),
    ]
