# Generated by Django 2.2.6 on 2019-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/')),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('civil law', 'CIVIL LAW'), ('criminal law', 'CRIMINAL LAW'), ('family law', 'FAMILY LAW'), ('family law writs', 'FAMILY LAW WRITS'), ('labour laws', 'LABOUR LAWS'), ('service matters', 'SERVICE MATTERS'), ('consumer matters', 'CONSUMER MATTERS'), ('immigrations', 'IMMIGRATIONS'), ('consultants', 'CONSULTANTS')], default='civil law', max_length=30)),
            ],
        ),
    ]
