# Generated by Django 2.2.6 on 2019-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
