# Generated by Django 2.2.6 on 2019-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('civil law', 'CIVIL LAW'), ('criminal law', 'CRIMINAL LAW'), ('family law', 'FAMILY LAW'), ('writs', 'WRITS'), ('labour laws', 'LABOUR LAWS'), ('service matters', 'SERVICE MATTERS'), ('consumer matters', 'CONSUMER MATTERS'), ('immigrations', 'IMMIGRATIONS'), ('consultants', 'CONSULTANTS')], default='civil law', max_length=30),
        ),
    ]
